### PR TITLE
Qtox PC board added Chinese version.

### PR DESCRIPTION
**Pull request by Caipenghui**

### CODE REVIEW

**Comment by iphydf** [comment]
What exactly is the point of this PR?

**Comment by Zer0-One** [comment]
Nice try, China, but it'll be harder than that to sneak in a backdoor.

**Comment by Caipenghui** [comment]
No, you're both wrong. This software will never be famous.

**Comment by GrayHatter** [comment]
I've deleted a comment, because I have a strict no trolling rule.

This repo exists for code. Comments must be relevant to the code.

Because this pull was closed, and isn't a candidate for reopening, I'm also going to lock it now as well.

**Pull request closed without merging**
