### PR TITLE
Add TOX_ERR_BOOTSTRAP_FAIL

### PR DESCRIPTION
**Pull request by askmatey**

### CODE REVIEW

**Comment by iphydf** [comment]
Can you add a description as to why you're doing this?

**Comment by iphydf** [comment]
@askmatey:
1. "Unsuccessfully" should not be capitalised in the middle of a sentence.
1. "Unsuccessfully" doesn't say anything about the actual error condition. All other errors are also returned in case of unsuccessful execution.
1. Why did you make this change?

**Comment by askmatey** [comment]
I ran into this issue, while testing `toxcore` in sandboxed environments, especially on low level arm devices with limited POSIX support. The `TOX_ERR_BOOTSTRAP_BAD_HOST` error parameter was confusing, since `tox_bootstrap` sets this error when `getaddrinfo` fails primarily (see [toxcore/tox.c#L277-L297](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L277-L297)).

However, the function can also set this error, if the DHT bootstrap node `count` is `0` at the end. This assumes that

1. The return value of `ai_socktype` is different then `SOCK_DGRAM` (see [toxcore/tox.c#L291-L293](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291-L293))
2. The return value of `ai_family` is neither `AF_INET` nor `AF_INET6` (see [toxcore/tox.c#L299-L301](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L299-L301))

In the end, I was able to fix the error by patching the function, since the return value of `ai_family` was - in this special case - non-standard.

I am convinced that the function should set an different parameter if it fails to retrieve either 1.) the preferred socket type or 2.) the desired address family *for all* provided DHT bootstrap nodes and I am aware that a change of this function might effect other programs too.

**Comment by askmatey** [comment]
I ran into this issue, while testing `toxcore` in sandboxed environments, especially on low level arm devices with limited POSIX support. The `TOX_ERR_BOOTSTRAP_BAD_HOST` error parameter was confusing, since `tox_bootstrap` sets this error when `getaddrinfo` fails primarily (see [toxcore/tox.c#L277-L297](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L277-L297)).

However, the function can also set this error, if the DHT bootstrap node `count` is `0` in the end. This assumes that

1. The return value of `ai_socktype` is different then `SOCK_DGRAM` (see [toxcore/tox.c#L291-L293](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291-L293))
2. The return value of `ai_family` is neither `AF_INET` nor `AF_INET6` (see [toxcore/tox.c#L299-L301](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L299-L301))

In the end, I was able to fix the error by patching the function, since the return value of `ai_family` was - in this special case - non-standard.

I am convinced that the function should set an different parameter if it fails to retrieve either 1.) the preferred socket type or 2.) the desired address family *for all* provided DHT bootstrap nodes and I am aware that a change of this function might effect other programs too.

**Comment by askmatey** [comment]
I ran into this issue, while testing `toxcore` in sandboxed environments, especially on low level arm devices with limited POSIX support. The `TOX_ERR_BOOTSTRAP_BAD_HOST` error parameter was confusing, since `tox_bootstrap` sets this error when `getaddrinfo` fails primarily (see [toxcore/tox.c#L277-L297](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L277-L297)).

However, the function can also set this error, if the DHT bootstrap node `count` is `0` in the end. This assumes that

1. The return value of `ai_socktype` is different then `SOCK_DGRAM` (see [toxcore/tox.c#L291-L293](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291-L293))
2. The return value of `ai_family` is neither `AF_INET` nor `AF_INET6` (see [toxcore/tox.c#L299-L301](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L299-L301))

In the end, I was able to fix the error by patching the function, since the return value of `ai_family` was - in this special case - non-standard.

I am convinced that the function should set an different parameter if it fails to retrieve either 1.) the preferred socket type or 2.) the desired address family *for all* provided DHT bootstrap nodes - or in other words - `count` is `0`.

I am aware that a change of this function might effect other programs too.

**Comment by askmatey** [comment]
I ran into this issue, while testing `toxcore` in sandboxed environments, especially on low level arm devices with limited POSIX support. The `TOX_ERR_BOOTSTRAP_BAD_HOST` error parameter was confusing, since `tox_bootstrap` sets this error when `getaddrinfo` fails primarily (see [toxcore/tox.c#L277-L297](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L277-L297)).

However, the function can also set this error, if the DHT bootstrap node `count` is `0` in the end. This assumes that

1. The return value of `ai_socktype` is different then `SOCK_DGRAM` (see [toxcore/tox.c#L291-L293](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291-L293))
2. The return value of `ai_family` is neither `AF_INET` nor `AF_INET6` (see [toxcore/tox.c#L299-L301](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L299-L301))

In the end, I was able to fix the error by patching the function, since the return value of `ai_family` was - in this special case - non-standard.

I am convinced that the function should set an different parameter if it fails to retrieve either 1.) the preferred socket type or 2.) the desired address family *for all* provided DHT bootstrap nodes. I am aware that a change of this function might effect other programs too.

**Comment by askmatey** [comment]
I ran into this issue, while testing `toxcore` in sandboxed environments, especially on low level arm devices with limited POSIX support. The `TOX_ERR_BOOTSTRAP_BAD_HOST` error parameter was confusing, since `tox_bootstrap` sets this error when `getaddrinfo` fails primarily (see [toxcore/tox.c#L277-L297](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L277-L297)).

However, the function can also set this error, if the DHT bootstrap node `count` is `0` in the end. This assumes that

1. The return value of `ai_socktype` is different then `SOCK_DGRAM` (see [toxcore/tox.c#L291-L293](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L291-L293))
2. The return value of `ai_family` is neither `AF_INET` nor `AF_INET6` (see [toxcore/tox.c#L299-L301](https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.c#L299-L301))

In the end, I was able to fix the error by patching the function, since the return value of `ai_socktype` was - in this special case - non-standard (see #1548).

I am convinced that the function should set an different parameter if it fails to retrieve either 1.) the preferred socket type or 2.) the desired address family *for all* provided DHT bootstrap nodes. I am aware that a change of this function might effect other programs too.

**Pull request closed without merging**
