### PR TITLE
Add script to generate save files with custom keys

### PR DESCRIPTION
**Pull request by ittner**
Allow users to play with keys generated outside Tox core without
depending on features from any specific client. Just generate a
stub save file that every client will understand.

### CODE REVIEW

**Comment by stqism** [comment]
@ittner Neat idea, but submitting non-C code to toxcore is generally frowned upon.

Might I suggest somewhere like Tox/Tox-Misc?

**Comment by ittner** [comment]
@stqism Interesting. I didn't know about this repository and added the script to other/fun/ because I could not think of another place to submit it. I'm sure there more small useful tools out there that can be centralized there.

**Comment by nurupo** [comment]
@stqism well, we have some python code in /other/fun/

**Comment by stqism** [comment]
@nurupo I feel as if it should be moved. We can't keep polluting toxcore with non-toxcore related code.

**Comment by nurupo** [comment]
Not to mention that it goes well in hand with strkey.c and cracker.c. You can generate a vanity key pair with them and make a save file with that script.

@stqism
Then we could move the daemon, dht_boostrap and each of tox libs (4 of them) into separate repos : )

**Comment by louipc** [comment]
Yeah probably should strictly port everything to C, but I guess at least stick to only one other language so C and Python that's it. oh and autoconf and m4 and shell, ...

**Pull request merged**
