### PR TITLE
Change default groupchat name back to NSA Agent

### PR DESCRIPTION
**Pull request by stal888**
just like the good ol days

### CODE REVIEW

**Comment by novist** [comment]
Actually i do not think targeting wider audience of people plays well with this. Cool inside jokes as they are do not give a professional impression to average users.

**Comment by dubslow** [comment]
Which is why this wasn't merged lol

**Comment by novist** [comment]
Hmm well.. Figured since PR is not closed maybe its being considered.

**Comment by autious** [comment]
Yes, this shoud be closed. It's a potentially funny joke, but Tox isn't about fun.

**Pull request closed without merging**
