### PR TITLE
Add UPnP support

### PR DESCRIPTION
**Pull request by Ansa89**
Rebase of irungentoo/toxcore#969.

### CODE REVIEW

**Comment by Impyy** [comment]
I would like to have UPnP configurable in Tox_Options. Something like ``bool upnp_enabled;`` would suffice.

**Comment by GrayHatter** [comment]
@Ansa89 http://cdn.meme.am/instances/23956669.jpg

**Comment by tycho** [comment]
Tried this change out locally. Sadly failed to compile against miniupnpc v1.9.20151026:

```
../toxcore/network.c: In function ‘upnp_map_port’:
../toxcore/network.c:130:52: warning: passing argument 6 of ‘upnpDiscover’ makes integer from pointer without a cast [-Wint-conversion]
     devlist = upnpDiscover(1000, NULL, NULL, 0, 0, &error);
                                                    ^
In file included from ../toxcore/network.c:47:0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: expected ‘unsigned char’ but argument is of type ‘int *’
 upnpDiscover(int delay, const char * multicastif,
 ^
../toxcore/network.c:130:15: error: too few arguments to function ‘upnpDiscover’
     devlist = upnpDiscover(1000, NULL, NULL, 0, 0, &error);
               ^
In file included from ../toxcore/network.c:47:0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: declared here
 upnpDiscover(int delay, const char * multicastif,
 ^
```

The function prototype for upnpDiscover in miniupnpc is:
```
MINIUPNP_LIBSPEC struct UPNPDev *
upnpDiscover(int delay, const char * multicastif,
             const char * minissdpdsock, int localport,
             int ipv6, unsigned char ttl,
             int * error);
```

This is probably the change that broke it: https://github.com/miniupnp/miniupnp/commit/1da63faa4fff5cb30e5d4b848ceef80a292382b9

**Comment by tycho** [comment]
One way to fix would be to check if MINIUPNPC_API_VERSION is >= 14, and add a default TTL argument of 2 if so. Or just make it require MINIUPNPC_API_VERSION >= 14 at configure time.

**Comment by Ansa89** [comment]
@Impyy: done.
@tycho: done.
@GrayHatter: lol.

**Comment by Ansa89** [comment]
Superseded by irungentoo/toxcore#1539.

**Pull request closed without merging**
