### PR TITLE
New API for ToxAV

### PR DESCRIPTION
**Pull request by mannol**

### CODE REVIEW

**Comment by GrayHatter** [comment]
https://gist.github.com/GrayHatter/813aa67b7e12492392ea

**Comment by Chuongv** [comment]
There's one bug I noticed with this. If Alice calls Bob, and Bob answers with just setting the `audio_bit_rate`, Alice gets a callback state of 52, which is the following 

TOXAV_FRIEND_CALL_STATE_ACCEPTING_A
TOXAV_FRIEND_CALL_STATE_ACCEPTING_V

**Comment by mannol** [comment]
Thats because ACCEPTING_* is set on by default for both sides.
Wednesday, 29 July 2015, 06:15AM +02:00 from chuong vu <notifications@github.com>:

**Comment by mannol** [comment]
I'll deal with that once I get back.
Wednesday, 29 July 2015, 01:09AM +02:00 from GrayHatter <notifications@github.com>:

**Comment by GrayHatter** [comment]
@mannol would you be willing to change line 320 `TOXAV_FRIEND_CALL_STATE_FINISHED = 2,` to   `TOXAV_FRIEND_CALL_STATE_ONGOING = 2`

Then when a call is ended without error, you could simply set state = 0? that would make it a lot easier for clients to know if they have an ongoing call just by checking the last state?

Also uTox is using the same format for call states, so perhaps `TOXAV_CALLSTATE_FIRST_A?V` would be a better variable?

**Comment by GrayHatter** [comment]
@mannol if you approve I can write the PR too

**Comment by suhr** [comment]
@GrayHatter Consider using reviewable.io, it provides a nice way to comment lines.

---

Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[auto_tests/toxav_basic_test.c, line 44 \[r1\]](https://reviewable.io:443/reviews/irungentoo/toxcore/1375#-Jvp5JOOwWgsjdLiZBhT)** ([raw file](https://github.com/irungentoo/toxcore/blob/7d5de68364f83662a19e45e6e3ab021414178df5/auto_tests/toxav_basic_test.c#L44)):</sup>
Trailing space?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/irungentoo/toxcore/1375)

**Comment by GrayHatter** [comment]
@suhr github has a good method too, but I know mannol is out of communications reach right now but still able to access email. So I formatted my message so that it's clear and obvious question that could be answered back via email.

**Comment by Chuongv** [comment]
Isn't setting it to 0, meant for showing that the call is paused? That's how Antidote is using that state right now.

**Comment by Chuongv** [comment]
@mannol I got video to work but only at 192 by 144 height/width. ToxAV seems to complain if I try to go any higher. I played around with different bit rates and resolutions, but no luck. You have any advice?

**Comment by mannol** [comment]
@Chuongv Define complains.
@GrayHatter That would complicate things even more IMO.

**Comment by Chuongv** [comment]
I am getting a TOXAV_ERR_SEND_FRAME_INVALID. When stepping through the debugger, I am failing at the `vpx_codec_enc_config_set`. https://gist.github.com/Chuongv/36541ee6b25862d7863b

**Comment by Chuongv** [comment]
To be more specific, I am getting VPX_CODEC_INVALID_PARAM

**Comment by GrayHatter** [comment]
@mannol I disagree...

right now, if both parties are in a video call you have 00111100, then if they both put the call on hold the state becomes 00000000.

But if you accept my changes

A video call will be 00111110, a state is which both sides have put the call on hold will be 00000010. That way a simple if (state) {} tells me if there's an active call.



Then as a client, all I have to do is if through my list of friends to see if anyone has an active call, and who I need to send frames too.

If one side disconnects, in the current system, I can't just save a state of 00000010, without also having a separate variable to know if I'm in call, or if the state is uninitialized, or on hold, or other.

**Comment by Chuongv** [comment]
>right now, if both parties are in a video call you have 00111100, then if they both put the call on hold the state becomes 00000000.

Which seems fine to me

>A video call will be 00111110, a state is which both sides have put the call on hold will be 00000010. That way a simple if (state) {} tells me if there's an active call.

I don't see how this is different than just using 00000000

>If one side disconnects, in the current system, **I can't just save a state of 00000010**, without also having a separate variable to know if I'm in call, or if the state is uninitialized, or on hold, or other.

I am having trouble understanding this. Why can't you have it as 00000010 (aka TOXAV_FRIEND_CALL_STATE_FINISHED)

Are you asking for this because you want to use the call states to differentiate between a dialing call and one that is active/ongoing?

**Comment by GrayHatter** [comment]
@Chuongv with my method I can `if (state) {}` and it'll return true no matter what state the call is in. Then if true I can handle other states of the call. If the call has ended successfully; I'll get a call back of state = 0, so the other party has disconnected the call.

With the way it is now, if the other party disconnects state = 2, and if they just put the call on hold state = 0.

In otherwords `if (true)` call is ended, but maybe also running, but maybe an error, but something. and `if (false)`, call never existed, or it's currently on hold, again you have to guess, or store an extra variable.

With my suggestion, `if (true)` this call is in progress or in error state. `if (false)` no call.

**Comment by GrayHatter** [comment]
@mannol when's the next commit getting pushed?

**Comment by GrayHatter** [comment]
Segfault on hangup when ending a ringing call, only when debugging is enabled in core.

From uTox/new_av_api branch.

@mannol 

```
[Switching to Thread 0x7ffff7f30700 (LWP 12424)]
0x00007ffff4de6d63 in pthread_mutex_trylock () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff4de6d63 in pthread_mutex_trylock () from /usr/lib/libpthread.so.0
#1  0x00000000004b03ca in msi_hangup (call=0x7fffe40ca370) at ../toxav/msi.c:220
#2  0x00000000004aebb5 in toxav_call_control (av=0x7fffe40c8ad0, friend_number=<optimized out>, control=<optimized out>, error=0x7ffff7f1fb00) at ../toxav/toxav.c:443
#3  0x000000000049ab5b in utox_av_local_disconnect (av=0x7fffe40c8ad0, friend_number=14) at utox_av.c:72
#4  0x000000000042f5b5 in tox_thread_message (tox=0x7fffe4009aa0, av=0x7fffe40c8ad0, time=6166672789862617, msg=25 '\031', param1=14, param2=1, data=0x0) at tox.c:1055
#5  0x000000000042dd00 in tox_thread (UNUSED_args=0x0) at tox.c:614
#6  0x00007ffff4de44a4 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff4b2213d in clone () from /usr/lib/libc.so.6
```

**Comment by mannol** [comment]
@GrayHatter 
> ... only when debugging is enabled in core.

That sounds suspicious. Also, that particular part was left (almost) unchanged. I doubt that's an issue. Can you check with valgrind?

**Comment by GrayHatter** [comment]
> That sounds suspicious. Also, that particular part was left (almost) unchanged. I doubt that's an issue. Can you check with valgrind?

my guess is pthread mutex is being all emotional from the logger.

I'll valgrind once @Chuongv brings his bot back online...

**Comment by Chuongv** [comment]
@GrayHatter I'll start up the bot up in a few hours. Though it's still on the old toxav, before the codec fix. Which I don't think it is compatible with the old? Anyways I'll try and see if I can update objcToxAV soon. Soon meaning, Thursday at the latest.

**Comment by zetok** [comment]
> autogen.sh 100755 → 100644

Why? this change breaks instructions in INSTALL.md, please revert.

**Comment by zetok** [comment]
> > autogen.sh 100755 → 100644

> Why? this change breaks instructions in INSTALL.md, please revert.

Oh well, should be fixed in https://github.com/mannol/toxcore/pull/3

**Comment by Chuongv** [comment]
Just tested this with objcTox and this looks good :+1: I am now able to push higher video resolution on mobile :smile:

**Comment by GrayHatter** [comment]
uTox will be ready to merge this in 1h or less...

- [x] uTox @grayhatter
- [ ] qTox @tux3
- [ ] Toxic @JFreegman 
- [ ] Antidote @Chuongv 
- [ ] Other?

**Comment by subliun** [comment]
Once new av is merged I'll finally be able to get on with implementing audio without losing my sanity (hopefully). As long as the adaptive bitrate and memory usage bugs have been fixed this is good to merge.

**Comment by subliun** [comment]
I spoke to soon... There are still issues with the docs that need fixing before this can be merged.
https://github.com/mannol/toxcore/blob/new_api/toxav/toxav.h#L513-L518 <- shouldn't have 'audio' in the description as it is for both audio and video

**Comment by tux3** [comment]
qTox will be ready today, as soon as I get the time to rebase the new av branch.

**Comment by dvor** [comment]
Antidote is ready to merge new av (basically we didn't have old av, we were using a new one straightaway).

**Comment by mannol** [comment]
@subliun c7336baf

Toxic has semi-complete new av fork that I'll complete tonight.

**Comment by SkyzohKey** [comment]
Ricin will implement new A/V API when merged ;)

**Comment by GrayHatter** [comment]
merging tomorrow! (assuming no hitches)

**Comment by benwaffle** [comment]
:+1:

**Comment by Chuongv** [comment]
Tomorrow will be a glorious day :tada:

**Comment by codedust** [comment]
:+1:

**Comment by TheNain38** [comment]
Yes ! It will be a big step forward :)

**Comment by scratch-net** [comment]
Countdown, maybe?

**Comment by GrayHatter** [comment]
@mannol segfault in toxav_iterate when starting -> ending call -> resending, canceling before accepting

```
(gdb) thread 3
[Switching to thread 3 (Thread 0x7fffeabc0700 (LWP 32047))]
#0  0x00000000004ae809 in toxav_iterate (av=0x7fffe4008640) at ../toxav/toxav.c:246
(gdb) bt
#0  0x00000000004ae809 in toxav_iterate (av=0x7fffe4008640) at ../toxav/toxav.c:246
#1  0x000000000049b515 in toxav_thread (args=0x7fffe4008640) at utox_av.c:62
#2  0x00007ffff4de14a4 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff4b1f13d in clone () from /usr/lib/libc.so.6
```

```
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff7f32700 (LWP 32046))]
#0  0x00007ffff4de9cfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff4de9cfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007ffff4de3bb2 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00000000004ae4eb in call_kill_transmission (call=0x7fffe40fe300) at ../toxav/toxav.c:1232
#3  0x00000000004afc84 in call_kill_transmission (call=0x7fffe40fe300) at ../toxav/toxav.c:416
#4  toxav_call_control (av=0x7fffe4008640, friend_number=<optimized out>, control=<optimized out>, error=0x7ffff7f21b40) at ../toxav/toxav.c:451
#5  0x000000000049b596 in utox_av_local_disconnect (av=0x7fffe4008640, friend_number=5) at utox_av.c:95
#6  0x000000000042f6dc in tox_thread_message (tox=0x7fffe4008820, av=0x7fffe4008640, time=7545396639735943, msg=27 '\033', param1=5, param2=1, data=0x0) at tox.c:1071
```

**Comment by GrayHatter** [comment]
and again if both clients try to end call at the same time 

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeab98700 (LWP 4202)]
0x00000000004ae809 in toxav_iterate (av=0x7fffe4008640) at ../toxav/toxav.c:246
(gdb) bt
#0  0x00000000004ae809 in toxav_iterate (av=0x7fffe4008640) at ../toxav/toxav.c:246
#1  0x000000000049b515 in toxav_thread (args=0x7fffe4008640) at utox_av.c:62
#2  0x00007ffff4de14a4 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff4b1f13d in clone () from /usr/lib/libc.so.6
(gdb) info threads
  Id   Target Id         Frame
  9    Thread 0x7fffdbb48700 (LWP 4209) "alsoft-mixer" 0x00007ffff4b1618d in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fffeab16700 (LWP 4204) "utox" 0x00007ffff4aee91d in nanosleep () from /usr/lib/libc.so.6
  4    Thread 0x7fffeab57700 (LWP 4203) "utox" 0x00007ffff4aee91d in nanosleep () from /usr/lib/libc.so.6
* 3    Thread 0x7fffeab98700 (LWP 4202) "utox" 0x00000000004ae809 in toxav_iterate (av=0x7fffe4008640) at ../toxav/toxav.c:246
  2    Thread 0x7ffff7f32700 (LWP 4201) "utox" 0x00007ffff4de9cfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
  1    Thread 0x7ffff7f33780 (LWP 4197) "utox" 0x00007ffff4b1784d in writev () from /usr/lib/libc.so.6
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff7f32700 (LWP 4201))]
#0  0x00007ffff4de9cfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff4de9cfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007ffff4de3bb2 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00000000004ae4eb in call_kill_transmission (call=0x7fffe40ab350) at ../toxav/toxav.c:1232
#3  0x00000000004afc84 in call_kill_transmission (call=0x7fffe40ab350) at ../toxav/toxav.c:416
#4  toxav_call_control (av=0x7fffe4008640, friend_number=<optimized out>, control=<optimized out>, error=0x7ffff7f21b40) at ../toxav/toxav.c:451
#5  0x000000000049b596 in utox_av_local_disconnect (av=0x7fffe4008640, friend_number=5) at utox_av.c:95
#6  0x000000000042f6dc in tox_thread_message (tox=0x7fffe4008820, av=0x7fffe4008640, time=7546180574505060, msg=27 '\033', param1=5, param2=1, data=0x0) at tox.c:1071
#7  0x000000000042ded0 in tox_thread (UNUSED_args=0x0) at tox.c:621
#8  0x00007ffff4de14a4 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff4b1f13d in clone () from /usr/lib/libc.so.6
```

**Comment by mannol** [comment]
@GrayHatter May I have valgrind or asan output?

**Comment by irungentoo** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7228700 (LWP 4575)]
0x00000000010c586c in toxav_iterate (av=0x60f000007750) at ../toxav/toxav.c:246
246                 if (i->msi_call->self_capabilities & msi_CapRAudio &&
#0  0x00000000010c586c in toxav_iterate (av=0x60f000007750) at ../toxav/toxav.c:246
#1  0x0000000000b917bb in toxav_thread (args=0x60f000007750) at utox_av.c:62
#2  0x0000003de8608314 in start_thread () from /lib64/libpthread.so.0
#3  0x0000003de7ae683d in clone () from /lib64/libc.so.6
(gdb) print av->calls_head
$1 = 0
(gdb) print *av->calls[av->calls_head]
$2 = {av = 0x60f000007750, mutex_audio = {{__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, 
        __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, audio = {first = 0x60600002b940, 
    second = 0x60d00002d6a0}, mutex_video = {{__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, 
        __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, video = {first = 0x60600002b8e0, 
    second = 0x61100001da00}, bwc = 0x60d00002d770, active = false, msi_call = 0x0, friend_number = 0, audio_bit_rate = 32, 
  video_bit_rate = 3000, previous_self_capabilities = 52 '4', mutex = {{__data = {__lock = 2, __count = 1, __owner = 4575, 
        __nusers = 1, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = "\002\000\000\000\001\000\000\000\337\021\000\000\001\000\000\000\001", '\000' <repeats 22 times>, 
      __align = 4294967298}}, prev = 0x0, next = 0x0}

```

This is what I fixed with: https://github.com/irungentoo/toxcore/commit/3949984c37538e4390eec52f28a992bfd88cfac5

**Comment by mannol** [comment]
oooooooh

**Comment by towlie** [comment]
@manol So https://github.com/mannol/toxcore/commit/7972db5c41b1cd573e4ba362d5d76ad4cd691c9f should be reverted?

**Comment by mannol** [comment]
@towlie yes

**Comment by GrayHatter** [comment]
That bug has been fixed, just need one more person/client to verify it's fixed.

**Comment by towlie** [comment]
Those who try to compile for windows should change https://github.com/irungentoo/toxcore/pull/1375/files#diff-0cafd7a68d158d90806473d52d84666cR140
To:
```
#pragma pack(1)
struct BWCMessage {
    uint8_t core_type; /* Aligner for payload type which is always 196 */

    uint32_t lost;
    uint32_t recv;
} __attribute__((packed));
#pragma pack()
```

until mannol pushes the fix

**Comment by dvor** [comment]
Woo hoo! :tada:

**Comment by Chuongv** [comment]
Is this real life?

**Comment by Impyy** [comment]
What have we done...

**Comment by benwaffle** [comment]
:ok_hand: :ok_hand: :ok_hand: :100:

**Comment by GrayHatter** [comment]
Thanks @mannol !!! We all love you!

**Comment by mannol** [comment]
No homo.

**Comment by quininer** [comment]
This is a big update, and perhaps should publish a releases to celebrate?

**Pull request merged**
