### PR TITLE
Added ablity to send keyframes lossless

### PR DESCRIPTION
**Pull request by GrayHatter**
[Review on Reviewable](https://reviewable.io/reviews/irungentoo/toxcore/1525)

### CODE REVIEW

**Comment by GrayHatter** [comment]
@irungentoo @mannol

**Comment by GrayHatter** [comment]
- [ ] acking the lossless frames

> CGM: we wont use core's lossless queue
> CGM: wo don't want core's congestion control

- [ ] and then a listerner for each ack?
- [ ] and then a handler to resend the frame if I don't get an ack in RTT*2
- [ ] and plug that into tox_iterate or toxav_iterate?

> CGM: but don't forget, you are doing it for the greater good

**Comment by GrayHatter** [comment]
rebased @mannol

**Comment by mannol** [comment]
Neat. I'll check it out in couple of days when i get back from my vacation.

**Comment by GrayHatter** [comment]
it's the the middle of a refactor. I'll pine you and some others one I'm done.

**Comment by mannol** [comment]
I thought you were done. I was aroused.

**Comment by GrayHatter** [comment]
I was, then I decided to make it better...

**Comment by GrayHatter** [comment]
updated

**Comment by seanlaguna** [comment]
Need any help?

**Comment by GrayHatter** [comment]
@seanlaguna sure, currently toxav dumps SO many packets into the lossless queue that friends lose connections.

my next step is to look into the two functions from net_crypto.c

```
_Bool max_speed_reached(Net_Crypto *c, int crypt_connection_id)
uint32_t crypto_num_free_sendqueue_slots(const Net_Crypto *c, int crypt_connection_id)
```

to see if they can be used to decide if we send the next keyframe lossless or lossy

I have no idea if either will work the way I'm expecting them too, but I've been distracted by some other work, so I haven't had a time to add more code to this.

another option is to ACK the lossless keyframes and only then start sending the lossy frames again

It would TRASH the frame rate, but you'd get higher quality

**Comment by mannol** [comment]
What about not using core lossless queue?

**Comment by GrayHatter** [comment]
@mannol I probably won't use it anymore, ToxAV needs way to much bandwidth and is choking out the important traffic. But re-implementing a send queue in ToxAV feels wrong. Not to mention it's way to much work when I have other projects that need more time as well.

**Pull request closed without merging**
