### PR TITLE
Spelling mistake nativly -> natively

### PR DESCRIPTION
**Pull request by bilalba**
Simple spelling mistake.

### CODE REVIEW

**Comment by GrayHatter** [comment]
@irungentoo

**Comment by ProMcTagonist** [comment]
why close

**Comment by GrayHatter** [comment]
because it's been open for a year, and @irungentoo still hasn't merged it, it's never going to get merged unless it's wrapped it a more helpful PR

**Comment by ProMcTagonist** [comment]
>it's never going to get merged unless it's wrapped it a more helpful PR

Why not?

**Comment by GrayHatter** [comment]
you'd have to ask @irungentoo

**Comment by ProMcTagonist** [comment]
So perhaps until he decides for himself we should leave the pull request open

**Comment by GrayHatter** [comment]
well the origination repo is now gone, so I couldn't reopen this, even if I wanted to. Which I don't, 

But if you want to go through and clean up a lot of the documentation, that would be really helpful.

**Pull request closed without merging**
