### PR TITLE
Added some diagrams describing the DHT protocol datapackets

### PR DESCRIPTION
**Pull request by arucard21**
I created some diagrams of the datapackets used in the DHT protocol while reading through the documentation. I thought it might be useful to include them in the existing documentation.

### CODE REVIEW

**Comment by dubslow** [comment]
Hilarious how this failed without even changing any code

**Comment by arucard21** [comment]
Yeah, I'm not sure if I did something wrong, kinda assumed someone would tell me if I did.

**Comment by urras** [comment]
Don't worry about it, sometimes make check fails randomly (see #1248)

**Comment by zetok** [comment]
Is there a reason to use `.png` rather than `.svg`?

**Comment by arucard21** [comment]
No real reason other than that I created these in GIMP and don't really know how to create svg files.

**Comment by codedust** [comment]
Inkscape is a great tool for that. ;)

**Comment by GrayHatter** [comment]
Closing as stale, I'll re-open this if anyone wants to take over. @arucard21  @codedust

**Pull request closed without merging**
