### PR TITLE
Make semver changes as requested

### PR DESCRIPTION
**Pull request by GrayHatter**
@CeBe 
@iphydf 
@nurupo

---
This change is [Review on Reviewable](https://reviewable.io/reviews/irungentoo/toxcore/1535)

### CODE REVIEW

**Comment by quininer** [comment]
This is awesome, I also want to `git tag` and `soname`.

**Comment by nurupo** [comment]
Why didn't you push [tox.in.h](https://github.com/irungentoo/toxcore/blob/master/other/apidsl/tox.in.h) and [toxav.in.h](https://github.com/irungentoo/toxcore/blob/master/other/apidsl/toxav.in.h) those tox.h and toxav.h were generated from?

**Comment by cebe** [comment]
looks good, except @nurupo's comment. Why is the version 0 in these files? https://github.com/irungentoo/toxcore/blob/master/other/apidsl/tox.in.h#L145-L160

**Comment by GrayHatter** [comment]
@nurupo @cebe updated

**Comment by GrayHatter** [comment]
@cebe updated

**Comment by cebe** [comment]
here is a diff view without whitespace changes: https://github.com/irungentoo/toxcore/pull/1535/files?w=0

**Comment by nurupo** [comment]
How can it look good to you if Travis-CI says that there is an error?

@GrayHatter In the tox.h you have in PR, there are places where you have `ToxAV` when it needs to be `Tox` https://travis-ci.org/irungentoo/toxcore/jobs/115968958#L952

**Comment by cebe** [comment]
Sorry, I have only looked at the code changes regarding versioning and assumed everything else to be okay.

**Pull request closed without merging**
