### PR TITLE
Tweaks to the new API

### PR DESCRIPTION
**Pull request by dubslow**
@irungentoo @nurupo @JFreegman 

The first commit should be included regardless, but I submit the second for discussion. (View it separately from the first.)

### CODE REVIEW

**Comment by Astonex** [comment]
If the one commit should definitely be included whilst the other is more subject to review, wouldn't it make sense to separate them into 2 pull requests?

**Comment by irungentoo** [comment]
yes I would prefer one pull request per change to save myself some trouble.

**Comment by dubslow** [comment]
Well I expect 95%+ of the other commits to be merged as well; a lot of discussion that I was asking for happened in IRC, and nurupo JFreegman largely concurred on the others as well. @irungentoo You'll have to review the changes one way or the other, I don't see the difference that two PRs makes...

**Comment by dubslow** [comment]
I force pushed only the const commit, I'll break down the other one into its component changes and make a bunch of PRs for those

**Pull request merged**
