### PR TITLE
[WIP] New group chats

### PR DESCRIPTION
**Pull request by ingvar1995**
_IMPORTANT NOTE: I opened this PR ~just for lulz~ just to tell you that some Tox devs are still alive. I know that even done NGC won't be merged because nobody is really interested in working NGC for some reasons_

**Some technical information:** 
Private NGC seems to work over both TCP/UDP now, but one hack still need to be fixed.
Public NGC are still as dead as irungentoo. I have few ideas how to fix it but I'm too busy to try these solutions.

**TODO:**
Public NGC fix
Some useful improvements

There are a lot of things that I wanna write here but github isn't really good place for this purpose. I will say only one thing: Tox needs restart, otherwise it will die. 

Good luck to anyone who want to continue my work.

### CODE REVIEW

**Comment by subliun** [comment]
what a meme

**Comment by GrayHatter** [comment]
> Public NGC are still as dead as irungentoo.

LOL

If you're willing to support this and keep working on it please one on my repo too https://github.com/GrayHatter/toxcore

**Comment by SkyzohKey** [comment]
Cool note ahah keep up good work m8 😂😂

**Comment by subliun** [comment]
This seems to break udp groupchats

**Pull request closed without merging**
