### PR TITLE
Strip the idea of friends from tox_connections

### PR DESCRIPTION
**Pull request by GrayHatter**
moved:    friend_connection.* -> tox_connection.*

Also stripped the idea of friends from these files.

Still TODO:
* Remove the idea of friends from the onion, and DHT.
* Write a Friend wrapper for Messenger.c to abstract tox_connection from messenger.c

Changes are pretty exclusively renaming the variables to be generic.

### CODE REVIEW

**Comment by SkyzohKey** [comment]
@GrayHatter Wouldn't it be better to simply change `friend` to `peer` ?

**Comment by Impyy** [comment]
``<@Jfreegman> it's probably not a good idea to prefix non-API function names with tox_``

See also: https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L727-L753

**Comment by GrayHatter** [comment]
@SkyzohKey no because peer has a different use in other places in toxcore.

@Impyy fixed

**Comment by GrayHatter** [comment]
cleaning out github history

closing as stale

**Pull request closed without merging**
