### PR TITLE
add new groupchats

### PR DESCRIPTION
**Pull request by wiiaam**

### CODE REVIEW

**Comment by ProMcTagonist** [comment]
much cleaner than current code, gj to all the developers involved

**Comment by Zer0-One** [comment]
this PR marks a milestone in the Toxcore codebase, can't wait to see it merged

**Comment by im-grey** [comment]
Wait, it's done now?

**Comment by GrayHatter** [comment]
@im-grey no, read the name of this branch

**Comment by wiiaam** [comment]
:disappointed:

**Comment by stal888** [comment]
😂👌👌👌👌💯

**Comment by subliun** [comment]
(Important note: This comment solely represents my own opinion and not those of the Tox project, or those of any of my past, present, or future employers.)

**Pull request closed without merging**
