### PR TITLE
Docker support for tox-bootstrapd

### PR DESCRIPTION
**Pull request by nurupo**
New features:

- Command line arguments
- Log to stdout. Available though command line argument switch
- Foreground mode, where the daemon doesn't detach from the terminal and doesn't write to the PID file. Available though command line argument switch
- Docker support

Breaks:

- Current users should update their init scripts before using this version of tox-bootstrapd, changing "tox-bootstrapd /etc/config/file/path" to "tox-bootstrapd --config /etc/config/file/path"

Note that the Docker image pulls list of bootstrap nodes from https://nodes.tox.chat/json

### CODE REVIEW

**Comment by GrayHatter** [comment]
@nurupo could you make pulling from nodes.tox.chat optional and a config option?

**Comment by nurupo** [comment]
>could you make pulling from nodes.tox.chat optional

You need to bootstrap into the main DHT network, so you need some nodes to bootstrap off. Docker is supposed to be just ran with zero configuration necessary, which is what users will do. Moreover, it's a bit troublesome to get shell inside of a container as you need to be somewhat familiar with Docker's comamnds, edit Dockerfile appropriately and jump though some hoops. If we don't provide any nodes to bootstrap off, users will be running Docker containers with bootstrap nodes not connected to the main DHT network, which is pointless. There needs to be a list of bootstrap nodes one way or another. What I could do is remove the pulling from https://nodes.tox.chat/json and just hardcode current list of nodes in a file, put it in the repo and cat that into the config file inside of the Docker container instead.

>and a config option

I don't understand what you mean by that.

**Comment by nurupo** [comment]
Don't merge yet, I just noticed that the Docker container doesn't start on system startup, want to investigate that.

**Comment by Impyy** [comment]
I tested the Dockerfile. Seems to work just fine.

**Comment by nurupo** [comment]
The reason why it was not starting up was because I forgot to disable systemd tox-bootstrapd, which would bind to TCP ports, and when tox-bootstrapd in Docker would run later, it would fail to use the same TCP ports.

Everything is fine and can be merged.

**Pull request merged**
