### PR TITLE
Add clarification where to find the public key.

### PR DESCRIPTION
**Pull request by aroneiermann**

### CODE REVIEW

**Comment by GrayHatter** [comment]
@aroneiermann are you sure that's where it's going to go for every distro?

**Comment by quininer** [comment]
systemd users need to check `journalctl`.

**Comment by GrayHatter** [comment]
stale

**Comment by quininer** [comment]
You should incorporate it in time, rather than waiting for it to corruption and then close...

**Comment by GrayHatter** [comment]
@quininer I'd rather not close it at all, but I'm not invested enough to clone and fix it myself. So 2 months later, I think it's time to close it and see if anyone else watching wants to fix this.

**Pull request closed without merging**
