### PR TITLE
small typo change

### PR DESCRIPTION
**Pull request by Jeeppler**
Alice adds bob -> Alice adds Bob

### CODE REVIEW

**Comment by GrayHatter** [comment]
:+1:

**Comment by itsrachelfish** [comment]
This pull request does not fix the lowercase "bob" on the following line, nor does it address the improper punctuation of "Bobs"

**Comment by Jeeppler** [comment]
it should fix the lowercase "bob" in line 12

**Comment by itsrachelfish** [comment]
Yeah man, and it says "bob" again on line 14.

**Comment by itsrachelfish** [comment]
If you're gonna fix one why not fix both?

**Comment by JFreegman** [comment]
If this gets merged I'm quitting Tox forever

**Comment by Jeeppler** [comment]
@JFreegman hey, I just wanted to commit some small change, to try out how it works. Is this the way to welcome new contributors? 

@itsrachelfish it did not saw the second one and I don't know about the punctuation. 

And actually I don't now how to revoke a pull request.

Honestly, I don't understand why this pull request gets so much attention.

**Comment by Impyy** [comment]
@Jeeppler There is no need to revoke this pull request, if you want you can push another commit to the same branch and it'll end up here ;)

The reason this got so much attention is because your change is very small and didn't fix the other instances of that error. Of course all contributions are welcome, no matter how small, but it would be nice if you could also fix that other capitalization error while you're at it.

Also please don't take @JFreegman's comment too seriously, he's only joking around :)

**Comment by JFreegman** [comment]
@Jeeppler 
Just having some fun. But you have to admit it's pretty absurd to make a pull request for one correction when the document is filled with similar errors. Why not fix the entire thing up?

**Pull request closed without merging**
