### PR TITLE
Add MARKDOWN message type.

### PR DESCRIPTION
**Pull request by zetok**
Needed by https://github.com/tux3/qTox/issues/2497

### CODE REVIEW

**Comment by optimumtact** [comment]
You should probably attempt to build consensus around this change on the TCS standards pull so that every client is on board with how it will work. Although I can't say I'm opposed to this in any way.

**Comment by zetok** [comment]
>You should probably attempt to build consensus around this change on the TCS standards pull so that every client is on board with how it will work.

If I wanted to engulf myself in bullshit, I would do this.

**Comment by Impyy** [comment]
I think we should wait until https://github.com/Tox/Tox-Client-Standard/pull/25 presents a conclusion on how this is going to work exactly.

**Comment by anoadragon453** [comment]
I agree there should be a standard, but we've spent quite a long while arguing about how the spec should be presented, and barely any discussion towards how it should be implemented.

**Comment by nurupo** [comment]
@anoadragon453 TCS doesn't dictate any specific implementation, it just specifies how things should work, which can be implemented in many different ways. The actual markdown implementation conforming to TCS is for clients to decide, so you won't see this discussion in either TCS or toxcore issue tracker, this discussion belongs to the issue tracker of a client application.

**Comment by anoadragon453** [comment]
@nurupo Sorry for being vague, I meant in terms of the syntax - however looking through the discussion again I realize these things are being discussed. I suppose remembering it from last night at ~4am makes things a little hazy :)

**Comment by nurupo** [comment]
As far as this PR goes, I wonder if there is any need in a separate message type for markdown. Why the `TOX_MESSAGE_TYPE_NORMAL` can't be used for it?

Introducing new message type is not a backwards-compatible change, so it shouldn't be done unless there is a concrete need in it. By "not a backwards-compatible change" I mean that client using older toxcore might not display messages of `TOX_MESSAGE_TYPE_MARKDOWN` type as they are not aware of such type.

So far I see one reason for introducing a separate message type instead of using `TOX_MESSAGE_TYPE_NORMAL`: users whose message was not meant to be interpreted as markdown but could be interpreted as markdown would be able to chose `TOX_MESSAGE_TYPE_NORMAL` so that the receiver party would see the message as it is, not interpreted as markdown.

**Comment by anoadragon453** [comment]
The argument is that using markdown would interfere with messages that contain codeblocks, or if people are trying to explain markdown syntax, their client will end up translating it automatically.

Honestly I think instead of a new message type, we should just have a separate sequence that will prevent markdown detection, such that anything inside will not be converted. "``" ?

Markdown is designed to look good and get the meaning across even without parsing.

And honestly as I'm attempting to implement this new message type, it's definitely a large change...

**Comment by anoadragon453** [comment]
@nurupo I commented with my own thoughts on the topic, hope you don't mind me quoting you.

As a developer though, a new message type would be ~50+ LoC change, while a syntax escape sequence would be ~5.

**Comment by zetok** [comment]
@nurupo 
>So far I see one reason for introducing a separate message type instead of using `TOX_MESSAGE_TYPE_NORMAL`: users whose message was not meant to be interpreted as markdown but could be interpreted as markdown would be able to chose `TOX_MESSAGE_TYPE_NORMAL` so that the receiver party would see the message as it is, not interpreted as markdown.

Yep, this very reason.

@anoadragon453 
>Honestly I think instead of a new message type, we should just have a separate sequence that will prevent markdown detection, such that anything inside will not be converted. "``" ?

How do you **ensure** that every client, current and the ones that will be made in the future will use that?

**Comment by anoadragon453** [comment]
How do you ensure every client updates their toxcore version, or keep up with any standard?

You can't, but it's quite likely they will if it's implemented into some sort of standard. At least if they don't, the meaning of each message will still be understandable.

**Comment by timofonic** [comment]
What about ASCIIDOC(TOR) + ADDONS (graphs, latex, etc)? :(

**Comment by zetok** [comment]
@anoadragon453 
>How do you ensure every client updates their toxcore version

Either they update, or become deprecated, simple as that. I.e. if client is alive, it's updated for the changes in toxcore, if it's not maintained any longer, then it doesn't.

>You can't, but it's quite likely they will if it's implemented into some sort of standard.

How do you know that it's likely? Could you give some data on that?

From my personal observation, it would seem that it works exactly in opposite way…

>At least if they don't, the meaning of each message will still be understandable.

And it should be still understandable, even if client won't parse in any special way `MARKDOWN` message type, and will display plaintext the way it was received.

@timofonic sorry, not a subject of this PR.

**Comment by anoadragon453** [comment]
As Tox clients currently stand, if a MARKDOWN-type message is received, would each client just display it as normal text? If so, then yeah, just stick the change in Toxcore and clients are good to start implementing parsing support.

If it breaks it, then clients are going to have to update anyways to support the new message type.

**Comment by nurupo** [comment]
A bit of offtopic.

>What about ASCIIDOC(TOR) + ADDONS (graphs, latex, etc)? :(

This actually leads to an interesting point. Markdown "source text" is made to be readable, but if in the future we decide to add some other message type, it might not be very human-readable, which will require a way to ask receiver's client whether such message type is supported by it.

This is not directly related to this issue and stands as a separate issue, but I guess it could be put aside until a non-human-readable message type is proposed to be added.

**Comment by anoadragon453** [comment]
@nurupo Yes, at that point you would __need__ parsing support implemented in each client. 

One step at a time.

**Comment by nurupo** [comment]
Actually, it's not offtopic. Having such functionality from the very start -- ability to ask the receiver client if it supports a message type -- would be very useful in this very case of adding Markdown support, as it would mitigate the backwards-compatibility issue I have mentioned. If the receiver is on an old toxcore, it would tell the sender that it doesn't support Markdown message type, so a client of the sender could send the markdown text as Normal message type.

>As Tox clients currently stand, if a MARKDOWN-type message is received, would each client just display it as normal text? 

It depends on the client implementation, as it might break a client in such a way that markdown message types won't be displayed on the receiving side or will be displayed as either Normal or Action message types.

**Comment by anoadragon453** [comment]
Yes, even if some consider LaTeX, ASCIIDOC, etc. support unnecessary, scalability is important, and we should make it relatively painless to add support for more syntaxes in the future.

We'll need a design for this functionality to propose.

**Comment by nurupo** [comment]
>As Tox clients currently stand, if a MARKDOWN-type message is received, would each client just display it as normal text? 

It depends on the client implementation, as it might break a client in such a way that markdown message types won't be displayed on the receiving side or will be displayed as either Normal or Action message types.

**Comment by anoadragon453** [comment]
I'd say just implement it in toxcore and watch as clients update over time. Almost every major dev is aware of the issue and is notified in the TCS PR. Tox is still is alpha and people will expect breakage which the latest client versions will fix.

**Comment by GrayHatter** [comment]
So, I'm very much for this idea. The question is, if the client drops the message. Will it be silent to the sender?

I.e., if I send a markdown msg to a client that does not' support markdown messages type, will I still get a message recept? Because that would be very bad.

**Comment by anoadragon453** [comment]
Yeah, so that was the issue that implementing it in the client would mitigate, because the user would still receive the message, but non-parsed, which with Markdown looks fine. 

But implementing it client side would definitely lead to fragmentation.

To answer your question: it depends on the client. I believe qTox will accept it fine, since it just marks everything that isn't an action message as a normal message.

**Comment by tux3** [comment]
(This is a copy of my post on the TCS markdown pull)

So I'm a bit late to the party, but I don't really see the need for a new message type. 

Markdown is made to be readable even without formatting, after all, so at least sending markdown as a normal message would give a good fallback for clients that don't implement markdown. 
And when people use markdown-like tags in chat it's usually for \*\*emphasis\*\*, so it doesn't harm either if we render that as **emphasized** text in normal messages.

**Comment by nurupo** [comment]
>So I'm a bit late to the party, but I don't really see the need for a new message type.
>
>Markdown is made to be readable even without formatting, after all, so at least sending markdown as a normal message would give a good fallback for clients that don't implement markdown. 
And when people use markdown-like tags in chat it's usually for **emphasis**, so it doesn't harm either if we render that as emphasized text in normal messages.

@tux3 see https://github.com/irungentoo/toxcore/pull/1502#issuecomment-173736975.

**Comment by JFreegman** [comment]
Reiterating from the other thread, I'm in agreement with @tux3.

**Comment by zetok** [comment]
[Proposed by @tux3](https://github.com/tux3/qTox/pull/2832#issuecomment-174102214) parsing of messages as MD by default + option for users to turn off parsing when they need it IMHO should do it.

Thus, I'm closing this PR, since it's not needed.

Thanks for all the feedback :)

**Comment by nurupo** [comment]
@zetok so, instead of the sender specifying to message's type to Normal and the receiver's client displaying it appropriately, you assume that the the receiver (a person) would realize that the received message could have been mistakenly parsed as markdown by the client and would turn off parsing for that message? This sounds horribly wrong to me.

**Comment by zetok** [comment]
@nurupo yep. Isn't that what everyone wants?

**Comment by ProMcTagonist** [comment]
@nurupo you should read through the linked issue

**Comment by GrayHatter** [comment]
I'm still for this PR.

The Toxcore API should explain that there are special message types that the user can handle. Then fall back to the default if it doesn't have a handler for that message type. 

What this PR does is tell the receiving client, "Hey the sender supports markdown, and I'm displaying this with markdown, you should too." The inverse being, if you send a normal message, and the sender doesn't support markdown, you might want to skip parsing the markdown syntax.

**Comment by GrayHatter** [comment]
Plus, by adding this, you effectively push everyone to handle messages correctly from the start. So that if we want to add a different message type in the future, we don't have to worry about breaking clients that don't adopt it right away. I.e. losing messages because they don't handle that message type.

**Comment by ProMcTagonist** [comment]
A new message type is unnecessary and bloats core. The point of markdown is being plain text. Read through the qTox discussion.

Entering a special markdown mode would be a pain and defeat the purpose of markdown.

Every message would be a markdown-type message. Pointless.

**Comment by GrayHatter** [comment]
> A new message type is unnecessary and bloats core. 

It's a single addition to an exist enum. You'd be hard pressed to call this bloat. (Also, new features aren't bloat)

>The point of markdown is being plain text. Read through the qTox discussion.

Actually, I disagree. I'd argue the point of markdown, to be both machine readable, as well as human readable. Saying that the point of markdown is to be plaintext is a gross misunderstanding of markdown.

> Entering a special markdown mode would be a pain and defeat the purpose of markdown.

It's 2 lines of code, and future proofs your code. This is a good thing.

> Every message would be a markdown-type message. Pointless.

No, this would actually be useful to clients that want to send preformatted messages. Knowing if the sending client is using markdown vs pre-formatted text would be useful when someone disables markdown.

**Comment by ProMcTagonist** [comment]
please reflect on your response to a UX concern with something about programming ease

**Pull request closed without merging**
