### PR TITLE
Change [[ to [

### PR DESCRIPTION
**Pull request by wedge-jarrad**
[[ is a Bash feature not available in sh.

### CODE REVIEW

**Comment by Zer0-One** [comment]
LGTM

**Comment by nurupo** [comment]
LGTM

**Comment by GrayHatter** [comment]
after reading http://mywiki.wooledge.org/BashFAQ/031 I think the $vars need to be quoted

:-1:

**Comment by wedge-jarrad** [comment]
Agreed. Fixed.

**Comment by GrayHatter** [comment]
👍

**Comment by iphydf** [comment]
@irungentoo merge this?

**Pull request merged**
