### PR TITLE
Add UPnP support.

### PR DESCRIPTION
**Pull request by shaunren**
Added UPnP support using libminiupnpc.

### CODE REVIEW

**Comment by LittleVulpix** [comment]
What's happening with this one? In general, tox (udp) seems to work better when ports are opened. Can I help with testing this? What needs to be done to merge this?

**Comment by BiTOk** [comment]
Why this PR was not merged to master?

**Comment by GrayHatter** [comment]
@BiTOk for a few reasons. The first few that comes to mind is that it merge conflics. no one else has tested it and posted here that it works. It's been silent for almost a year. And the submitter hasn't done anything with it for awhile

**Comment by towlie** [comment]
I tested it on windows and it worked. I saw that it added ports via UPnP.

**Comment by GrayHatter** [comment]
@shaunren any chance we could get you to rebase or merge master into this PR?

@towlie @BiTOk @LittleVulpix @cebe any of you want to take a stab at it if shaunren isn't around?
If so just use `git format-patch` and past the output here.

**Comment by nurupo** [comment]
>If so just use git format-patch and past the output here.

What about running Travis on it? A separate cross-referenced PR might be better.

**Comment by towlie** [comment]
The only problem I saw with this was that static linking failed. I could only use shared dll for linking. the static .a file was never used/found by toxcore configure.

**Comment by LittleVulpix** [comment]
I'll try to see if I can get it going somehow.

**Comment by GrayHatter** [comment]
@nurupo is right, a separate PR would be best

**Comment by GrayHatter** [comment]
And now that I think about it. What do you think about defaulting to compiling without this? Tox isn't exactly quiet on a network. But UPnP broadcasts would be quite telling as to who's running what on the network... Thoughts?

**Comment by BiTOk** [comment]
Maybe present it as a setting "Enable UPnP" and disable it by default?

**Comment by GrayHatter** [comment]
@BiTOk yeah, there's already a flag to disable it, just need to make that the default, and change the flag to optionally enable it

**Comment by BiTOk** [comment]
@GrayHatter I said about client setting, not about compiling setting.

**Comment by nurupo** [comment]
What does this UPnP support actually bring to Tox? How it is useful?

As far as I understand, it's used only for discovery of Tox nodes/clients running in LAN, i.e. it's functionality greatly overlaps with the one of LAN discovery Tox currently has. If so, then I don't see it bringing anything useful to justify a new library dependency (perhaps optional one).

**Comment by nurupo** [comment]
Also, there mist be a way to enable/disable it, so a new field in [`Tox_Options`](https://github.com/irungentoo/toxcore/blob/f3b65bc3dc4f85924ddf7f2cf453924963b5e989/toxcore/tox.h#L391) struct would be required. (That essentially means that a Tox must be restarted in order to enable/disable it.)

**Comment by LittleVulpix** [comment]
@nurupo upnp configures upnp-compatible(and enabled) routers for port forwarding. In other words, it will automatically make your router forward 33445 to you (or whichever port your tox decides to use), which improves tox networking, especially in udp mode.

**Comment by GrayHatter** [comment]
@nurupo much more reliable then UDP hole punching

**Comment by nurupo** [comment]
Ok, then I have misunderstood it. Sounds good to me, the dependency is justified :)

**Comment by BiTOk** [comment]
As I can understand, this can increase file transfer speed and decrease tox network load (transfer without tcp relay. I correctly understood?

**Comment by fcore117** [comment]
towlie: what do you mean cannot statically linked? does it mean we should forget single .exe or binary releases or it is something else? i am not programmer.

**Comment by towlie** [comment]
@fcore117 It means that I had to use an extra dll file. So no single .exe binary. I assume that this is fixable with some research. Because it produces an static linkable .a file but somehow toxcore wasn't able to use it.

**Comment by LittleVulpix** [comment]
I've been defeated by rebasing, I can't do it. It's up to @shaunren or the other warriors now!

**Comment by GrayHatter** [comment]
Closing as stale, I'll re-open this if anyone wants to take over. @irungentoo @shaunren

**Pull request closed without merging**
